/**
 * Amplify client configuration.
 * Reads from amplify_outputs.json generated by `npx ampx sandbox` or CI deploy.
 * Falls back gracefully if the file is not present (local dev without backend).
 */

let amplifyConfigured = false;

export async function configureAmplify() {
  if (amplifyConfigured) return;
  try {
    const { Amplify } = await import("aws-amplify");
    // amplify_outputs.json is generated by `npx ampx sandbox` or CI deploy
    const outputs = await import("../../amplify_outputs.json").catch(
      () => null
    );
    if (outputs) {
      Amplify.configure(outputs.default ?? outputs, { ssr: true });
      amplifyConfigured = true;
    }
  } catch {
    console.warn(
      "[Amplify] Could not load amplify_outputs.json — running in local/demo mode"
    );
  }
}

// ─── Storage helpers (localStorage + Amplify DataStore future) ────────────────

const STORAGE_KEYS = {
  FG: "st_fg_v1",
  PUNT: "st_punt_v1",
  KICKOFF: "st_kickoff_v1",
  LONGSNAP: "st_longsnap_v1",
  TEAM: "st_team_v1",
  AUTH: "st_auth_v1",
} as const;

export function localGet<T>(key: keyof typeof STORAGE_KEYS): T | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(STORAGE_KEYS[key]);
    return raw ? (JSON.parse(raw) as T) : null;
  } catch {
    return null;
  }
}

export function localSet<T>(key: keyof typeof STORAGE_KEYS, data: T): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEYS[key], JSON.stringify(data));
  } catch {
    console.warn("[Storage] Could not write to localStorage");
  }
}
